name:                Servant-rest
version:             0.1.0.0
github:              "githubuser/Servant-rest"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Servant-rest#readme>

dependencies:
- base >= 4.7 && < 5
- base-compat
- servant
- servant-server
- servant-lucid
- servant-client
- aeson
- wai
- warp
- lucid
- text
- time
- directory
- string-conversions
- mtl
- http-media
- http-client
- bytestring
- attoparsec
- sqlite-simple
- postgresql-simple
- HDBC
- HDBC-sqlite3
- beam-core
- beam-sqlite
- beam-postgres
- lens
- resource-pool

library:
  source-dirs: src

executables:
  Servant-rest-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Servant-rest

tests:
  Servant-rest-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Servant-rest
