name:                Servant-rest
version:             0.1.0.0
github:              "githubuser/Servant-rest"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/githubuser/Servant-rest#readme>

dependencies:
- base >= 4.7 && < 5
- base-compat
- servant
- servant-server
- servant-lucid
- servant-client
- aeson
- wai
- warp
- lucid
- text
- time
- string-conversions
- mtl
- http-media
- http-client
- bytestring
- attoparsec
- sqlite-simple
- postgresql-simple
- beam-core
- beam-sqlite
- beam-postgres
- lens
- resource-pool
- clock
- formatting

executables:
  server:
    main: Main.hs
    source-dirs:         
      - server/src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall

tests:
  spec:
    main: Spec.hs
    source-dirs:         
      - server/test
      - server/src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
